service: cloudwatchS3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - s3:GetObject
        - logs:StartQuery
        - logs:getQueryResults
      Resource:
        - "arn:aws:s3:::*"
        - "arn:aws:logs:*:*:*"

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  createSuma:
    handler: calculos.sumar
    events:
      - httpApi:
          path: /createsumar
          method: post
